#!/bin/bash

## Make folder
go_directory=$HOME/Go
mkdir -p $go_directory

## Install Dependencies
echo "\n" | /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew install boost cmake wget gnu-sed platypus
python2.7 --version || brew install python@2
java -version || brew cask install java

## Make apps
scripts="$( cd "$(dirname $0)" ; pwd -P )"/scripts
platypus --overwrite --name Lizzie --app-icon $scripts/Lizzie.icns $scripts/Lizzie.sh
mv -f $scripts/Lizzie.app $go_directory 
platypus --overwrite --name GoReviewPartner --app-icon $scripts/GoReviewPartner.icns $scripts/GoReviewPartner.sh
mv -f $scripts/GoReviewPartner.app $go_directory

## Build Leela Zero
cd $go_directory
git clone --recursive --branch next http://github.com/gcp/leela-zero.git
cd leela-zero
mkdir build && cd build # Use stand alone directory to keep source dir clean
cmake -DUSE_CPU_ONLY=1 ..
cmake --build .
./tests

## Lizzie
cd $go_directory
wget https://github.com/featurecat/lizzie/releases/download/0.6/Lizzie.0.6.Mac-Linux.zip
unzip Lizzie.0.6.Mac-Linux.zip
rm Lizzie.0.6.Mac-Linux.zip
cd Lizzie
ln -s ../leela-zero/build/leelaz .

## Go Review Partner
cd $go_directory
wget https://github.com/pnprog/goreviewpartner/archive/v0.14.2.zip
unzip v0.14.2.zip
rm v0.14.2.zip
cd goreviewpartner-0.14.2
gsed -i \
    -e '86s|^.*$|slowcommand = '$go_directory'/leela-zero/build/leelaz|'\
    -e '87s|^.*$|slowparameters = --gtp --noponder --weights '$go_directory'/Lizzie/network.gz|'\
    -e '89s|^.*$|fastcommand = '$go_directory'/leela-zero/build/leelaz|'\
    -e '90s|^.*$|fastparameters = --gtp --noponder --weights '$go_directory'/Lizzie/network.gz|' \
    config.ini

## test
cd $go_directory
ls
mkdir -p $go_directory/Games/Pro
cd $go_directory/Games/Pro
cp $scripts/1.sgf .
python2.7 $go_directory/goreviewpartner-0.14.2/leela_zero_analysis.py --no-gui --range 7-10 1.sgf
